---
# Default values for installer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nicholaswilde/installer
  pullPolicy: IfNotPresent
  tag: "0.2.9"

secret: {}
  # USER: ""
  # GH_TOKEN: ""

service:
  port:
    port: 3000

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.1.0/24
  hosts:
    - host: "installer.192.168.1.199.nip.io"
      paths:
        - path: "/"
          pathType: Prefix
  # tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

podAnnotations: {}
  # https://crazymax.dev/diun/providers/kubernetes/#kubernetes-annotations
  # Set to true to enable image analysis of this pod
  # diun.enable: "false"
  # Watch all tags of this pod image
  # diun.watch_repo: "false"
  ## Registry options name to use
  # regopt: ""
  ## Maximum number of tags to watch if diun.watch_repo enabled. 0 means all of them
  # max_tags: 0
  ## Semi-colon separated list of regular expressions to include tags. Can be
  ## useful if you enable diun.watch_repo
  # include_tags: ""
  ## Semi-colon separated list of regular expressions to exclude tags. Can be
  ## useful if you enable diun.watch_repo
  # exclude_tags: ""
