---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloud9.fullname" . }}
  labels:
    {{- include "cloud9.labels" . | nindent 4 }}
{{- with .Values.config }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
