{{- if and .Values.persistence.sock.enabled (not .Values.persistence.sock.existingClaim) }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metasock:
  name: {{ template "cloud9.fullname" . }}-sock
  {{- if .Values.persistence.sock.skipuninstall }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
  labels:
    {{- include "cloud9.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.sock.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.sock.size | quote }}
{{- if .Values.persistence.sock.storageClass }}
{{- if (eq "-" .Values.persistence.sock.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: {{ .Values.persistence.sock.storageClass | quote }}
{{- end }}
{{- end }}
{{- end -}}
