{{- if .Values.secret -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cloud9.fullname" . }}
  labels:
  {{- include "cloud9.labels" . | nindent 4 }}
type: Opaque
{{- with .Values.secret }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
