---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "diun.fullname" . }}
roleRef:
  name: {{ template "diun.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
subjects:
  - name: {{ template "diun.fullname" . }}
    namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
