{{- if .Values.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "diun.fullname" . }}
  labels:
  {{- include "diun.labels" . | nindent 4 }}
type: Opaque
{{- with .Values.secret }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
