---
apiVersion: v2
appVersion: 3.00
version: 0.1.5
name: transmission
description: A Fast, Easy, and Free BitTorrent Client.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/transmission"
keywords:
  - transmission
  - bittorrent
maintainers:
  - name: Nicholas Wilde
    email: ncwilde43@gmail.com
