---
apiVersion: v2
appVersion: 3.00
version: 0.1.10
name: transmission
description: A Fast, Easy, and Free BitTorrent Client.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/transmission"
icon: "https://raw.githubusercontent.com/transmission/transmission/master/web/public_html/images/webclip-icon.png"
keywords:
  - transmission
  - bittorrent
sources:
  - https://transmissionbt.com/
  - https://hub.docker.com/r/linuxserver/transmission
maintainers:
  - name: Nicholas Wilde
    email: ncwilde43@gmail.com
