apiVersion: v2
appVersion: 9e30fdd7
version: 0.1.5
name: smokeping
description: Keep track of your network latency.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/smokeping"
icon: "https://raw.githubusercontent.com/nicholaswilde/helm-charts/main/charts/smokeping/img/smokeping-icon.jpg"
dependencies:
- name: common
  version: ~0.1.7
  repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - smokeping
  - network
  - latency
sources:
  - https://oss.oetiker.ch/smokeping/
  - https://hub.docker.com/r/linuxserver/smokeping
maintainers:
  - name: Nicholas Wilde
    email: ncwilde43@gmail.com
