---
# Default values for Clarkson
image:
  repository: ghcr.io/linuxserver/clarkson
  pullPolicy: IfNotPresent
  tag: version-v1.1.2

strategy:
  type: Recreate

service:
  port:
    port: 3000

secret:
  MYSQL_USERNAME: admin
  MYSQL_PASSWORD: admin

env:
  TZ: "America/Los_Angeles"
  ENABLE_REGISTRATIONS: true
  MYSQL_HOST: mysql_host
  # PUID: "1001"
  # PGID: "1001"

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.1.0/24
  hosts:
    - host: "clarkson.192.168.1.199.nip.io"
      paths:
        - path: "/"
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

podAnnotations: {}
  # https://crazymax.dev/diun/providers/kubernetes/#kubernetes-annotations
  # Set to true to enable image analysis of this pod
  # diun.enable: "false"
  # Watch all tags of this pod image
  # diun.watch_repo: "false"
  ## Registry options name to use
  # regopt: ""
  ## Maximum number of tags to watch if diun.watch_repo enabled. 0 means all of them
  # max_tags: 0
  ## Semi-colon separated list of regular expressions to include tags. Can be
  ## useful if you enable diun.watch_repo
  # include_tags: ""
  ## Semi-colon separated list of regular expressions to exclude tags. Can be
  ## useful if you enable diun.watch_repo
  # exclude_tags: ""
