apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transmission.fullname" . }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
data:
  PGID: {{ .Values.config.pgid | quote }}
  PUID: {{ .Values.config.puid | quote }}
  TRANSMISSION_WEB_HOME: {{ .Values.config.transmission_web_home | quote }}
  TZ: {{ .Values.config.tz | quote }}
