{{- if and .Values.persistence.watch.enabled (not .Values.persistence.watch.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "transmission.fullname" . }}-watch
  {{- if .Values.persistence.watch.skipuninstall }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.watch.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.watch.size | quote }}
{{- if .Values.persistence.watch.storageClass }}
{{- if (eq "-" .Values.persistence.watch.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: {{ .Values.persistence.watch.storageClass | quote }}
{{- end }}
{{- end }}
{{- end -}}
