apiVersion: v1
kind: Secret
metadata:
  name: {{ template "transmission.fullname" . }}
  labels:
  {{- include "transmission.labels" . | nindent 4 }}
type: Opaque
data:
  USER: {{ .Values.secret.user | b64enc | quote }}
  PASS: {{ .Values.secret.pass | b64enc | quote }}
