apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: {{ .Values.service.portName | quote }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
{{ if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
    nodePort: {{.Values.service.nodePort}}
{{- end }}
{{- range .Values.service.additionalPorts }}
  - name: {{ .name | quote }}
    port: {{ .port }}
    targetPort: {{ .port }}
    protocol: {{ .protocol }}
{{- end }}
  selector:
    {{- include "transmission.selectorLabels" . | nindent 4 }}
