---
# Default values for template.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ghcr.io/linuxserver/projectsend
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "r1070-ls53"

secret: {}

env:
  # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  TZ: "America/Los_Angeles"
  PUID: "1000"
  PGID: "1000"
  MAX_UPLOAD: <5000>

service:
  port:
    port: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.1.0/24
  hosts:
    - host: "projectsend.192.168.1.203.nip.io"
      paths:
        - path: "/"
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

persistence:
  config:
    enabled: false
    emptyDir: false
    mountPath: /config
    accessMode: ReadWriteOnce
    size: 1Gi
    ## Do not delete the pvc upon helm uninstall
    skipuninstall: false
  data:
    enabled: false
    emptyDir: false
    mountPath: /data
    ## Template downloads data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    ##
    ## If you want to reuse an existing claim, you can pass the name of the PVC using
    ## the existingClaim variable
    # existingClaim: your-claim
    accessMode: ReadWriteOnce
    size: 1Gi
    ## Do not delete the pvc upon helm uninstall
    skipuninstall: false

podAnnotations: {}
  # https://crazymax.dev/diun/providers/kubernetes/#kubernetes-annotations
  # Set to true to enable image analysis of this pod
  # diun.enable: "false"
  # Watch all tags of this pod image
  # diun.watch_repo: "false"
  ## Registry options name to use
  # regopt: ""
  ## Maximum number of tags to watch if diun.watch_repo enabled. 0 means all of them
  # max_tags: 0
  ## Semi-colon separated list of regular expressions to include tags. Can be
  ## useful if you enable diun.watch_repo
  # include_tags: ""
  ## Semi-colon separated list of regular expressions to exclude tags. Can be
  ## useful if you enable diun.watch_repo
  # exclude_tags: ""
